name: API Continuous Integration

# Define quando o robô vai trabalhar (a cada push na branch main)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    # Cria uma máquina virtual limpa com Linux Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 1. Baixa o código do seu repositório para a máquina virtual
      - name: Check out the code
        uses: actions/checkout@v4

      # 2. Instala o Java 21 (Temurin)
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Dá permissão de execução para o Maven Wrapper (para evitar erros de permissão no Linux)
      - name: Make Maven Wrapper executable
        run: chmod +x mvnw

      # 4. Roda o comando que compila a API e executa todos os nossos testes!
      - name: Build and Test with Maven
        run: ./mvnw clean package